{
 "title": "Internet Speed",
 "tags": [ "Ookla" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ping packet loss",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ping_loss", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Average Ping latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_avg_latency", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Number of Traceroute hops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "tracert_hops_count", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "packet_loss{job=\"SpeedTest\", instance=\"Apps.Horna.local:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_jitter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "packet_loss{job=\"SpeedTest\", instance=\"Apps.Horna.local:8000\"}",
     "legendFormat": "Packet loss"
    }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "Download" },
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Transfer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "download_latency_high", "legendFormat": "Download Latency" },
    { "expr": "upload_latency_high", "legendFormat": "Upload Latency" }
   ]
  },
  {
   "title": "SpeedTests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "count by (url) (result_details_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SpeedTests Details",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "count by (url) (result_details_info)\n  * on() group_left(country, host, ip, location, name, port) server_details_info",
     "legendFormat": "__auto"
    },
    { "expr": "download_bandwidth / 1000000", "legendFormat": "__auto" },
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "__auto" },
    { "expr": "ping_no_workload_latency", "legendFormat": "__auto" }
   ]
  }
 ]
}